Sources/Library/Info.plist, Sources/Library/InstantSearch.swift
=> feat(user-agent): add user-agent to InstantSearch

Readme.md
All of the badges are blue, so this is nicer
=> docs(readme): make swift badge blue

docgen/layouts/archetypes/content-with-menu.pug, docgen/layouts/archetypes/single-column-formatted.pug, docgen/layouts/archetypes/single-column.pug, docgen/layouts/common/footer.pug
=> Removed standalone KM tracking and added GTM

docgen/src/troubleshooting.md
This seemed more natural to me
=> docs(troubleshooting): slightly change wording

docgen/src/data/communityHeader.json
Fixes #issue(s) .
Changes proposed in this request:
*
*
*
=> chore(doc): Add svg back fix #8

docgen/layouts/index.pug
=> Add is-vue tile

.jazzy.yaml, Tools/deploy-gh-pages.sh, docgen/package.json, docgen/src/getting-started.md, fastlane/Fastfile
=> feat(fastlane): add jazzy and publish website to fastlane

docgen/src/getting-started.md
=> docs(getting-started): tagline

InstantSearchTestsHost/Assets.xcassets/AppIcon.appiconset/Contents.json, Sources/Concrete/Controller/SpeechController.swift, instantsearch.xcodeproj/project.pbxproj
Fixes #issue(s) .
Changes proposed in this request:
*
*
*
=> feat(voiceSearch): Add the voice-search controller

Sources/Models and Helpers/Helpers.swift
Fixes #issue(s) .
Changes proposed in this request:
*
*
*
=> fix(memleak): Fixing the memory leak for the WeakSet with nil objects

Sources/InstantSearch.swift, fastlane/Fastfile
=> feat(custom-sources): multi-indexing support for custom backend

Sources/Concrete/Controller/HitsController.swift, Sources/Concrete/Controller/MultiHitsController.swift, Sources/Concrete/Controller/RefinementController.swift, Sources/Concrete/Controller/SpeechController.swift, Sources/Concrete/View/ActivityIndicatorView.swift, Sources/Concrete/View/DatePickerWidget.swift, Sources/Concrete/View/HitsCollectionWidget.swift, Sources/Concrete/View/HitsTableWidget.swift, Sources/Concrete/View/MultiHitsCollectionWidget.swift, Sources/Concrete/View/MultiHitsTableWidget.swift, Sources/Concrete/View/OneValueSwitchWidget.swift, Sources/Concrete/View/RefinementCollectionWidget.swift, Sources/Concrete/View/RefinementTableWidget.swift, Sources/Concrete/View/SearchBarWidget.swift, Sources/Concrete/View/SegmentedControlWidget.swift, Sources/Concrete/View/SliderWidget.swift, Sources/Concrete/View/StatsButtonWidget.swift, Sources/Concrete/View/StatsLabelWidget.swift, Sources/Concrete/View/StepperWidget.swift, Sources/Concrete/View/SwitchWidget.swift, Sources/Concrete/View/TextFieldWidget.swift, Sources/Concrete/View/TwoValuesSwitchWidget.swift, Sources/InstantSearch.swift, Sources/Models and Helpers/SearcherId.swift
Fixes #issue(s) .
Changes proposed in this request:
* Move from @objc to @objcMembers
=> fix(objc): Fix ObjC compatibility for Swift4

docgen/src/getting-started-part2.md
=> docs(guide): Remove word repetition in Getting Started (part 2)

Sources/InstantSearch.swift
=> feat(caching): Add searchCacheEnabled property

Cartfile.resolved, Sources/Concrete/ViewModel/RefinementMenuViewModel.swift
=> Use defer reloadRefinements instead of putting it everywhere

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new patch version 3.1.1

Sources/Concrete/View/RefinementCollectionWidget.swift, Sources/Concrete/View/RefinementTableWidget.swift, Sources/Concrete/ViewModel/RefinementMenuViewModel.swift, Sources/Models and Helpers/Constants.swift, Sources/Protocols/View-ViewModel/RefinementMenuViewDelegate.swift
=> Conjunctive refinement list: being able to select multiple refinements

Sources/Concrete/ViewModel/SearchViewModel.swift
=> Sovle bug of key observer for iOS 10 and below.

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new patch version 3.1.3

CHANGELOG.md, Readme.md, docgen/layouts/common/hero.pug, docgen/layouts/index.pug, docgen/mdRenderer.js, docgen/src/data/communityHeader.json, docgen/src/getting-started-part2.md, docgen/src/getting-started-programmatic.md
Forgot to push this. These changes are already deployed live.
=> Fix all links to the community website, and redirect to main docs

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new major version 4.0.0

Readme.md
=> Update readme.md for release

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new minor version 5.2.0

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new patch version 5.2.1

Sources/Controller/QuerySuggestions/QuerySuggestionsViewController.swift, Sources/Controller/SearchBox/TextFieldController.swift, instantsearch.xcodeproj/project.pbxproj
- Set `QuerySuggestionsViewController` conform to QueryInputController protocol
- Trigger query change for .editingDidEnd event of the UITextField
=> Fixes & Improvements

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new patch version 5.2.2

InstantSearch.podspec, InstantSearchTestsHost/Info.plist, Tests/Info.plist
=> Deploying new patch version 5.2.3

Readme.md
This PR adds a link to the FAQ.
=> docs: add link to FAQ

fastlane/Fastfile
Fix the issue with generate version file stage in Fastfile
=> Deployment script fix

InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> Deploying new patch version 7.0.1

fastlane/Fastfile
- Fix podspec name in the pod push stage
- Remove unnecessary comments
=> Yet another deployment script fix

Sources/InstantSearchCore/FacetList/FacetListConnector.swift
This PR adds missing `presenter` parameter to FacetListConnector.
=> Add presenter parameter to FacetListConnector

InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> Deploying new minor version 7.1.0

InstantSearch.podspec, Sources/InstantSearchCore/FilterList/Connector/FacetFilterListConnector.swift, Sources/InstantSearchCore/FilterList/Connector/FilterTypeAliases.swift, Sources/InstantSearchCore/FilterList/Connector/NumericFilterListConnector.swift, Sources/InstantSearchCore/FilterList/Connector/TagFilterListConnector.swift, Sources/InstantSearchCore/FilterState/Accessors/HierarchicalGroupAccessor.swift, Sources/InstantSearchCore/FilterState/FilterGroupID.swift, fastlane/Fastfile
**Summary**
Fixes ensuring a succesful Cocoapods linting
=> fix: Pod lint

InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> Deploying new minor version 7.2.0

Readme.md
This PR changes dependency version in Readme to avoid inconsistency with documentation and guides
=> Update dependency version in readme

Sources/InstantSearchCore/Helper/Decodable+JSON.swift, Sources/InstantSearchCore/QueryRuleCustomData/Connector/QueryRuleCustomDataConnector+Controller.swift, Sources/InstantSearchCore/QueryRuleCustomData/Connector/QueryRuleCustomDataConnector.swift, Sources/InstantSearchCore/QueryRuleCustomData/QueryRuleCustomDataInteractor+MultiIndexSearcher.swift, Sources/InstantSearchCore/QueryRuleCustomData/QueryRuleCustomDataInteractor+SingleIndexSearcher.swift, Sources/InstantSearchCore/QueryRuleCustomData/QueryRuleCustomDataInteractor.swift, Tests/InstantSearchCoreTests/Unit/QueryRuleCustomData/QueryRuleCustomDataSearcherConnectionTests.swift, Tests/InstantSearchTests/Snippets/QueryRuleCustomDataSnippets.swift, Tests/InstantSearchTests/Snippets/RedirectGuideSnippets.swift
**Summary**
Query Rule Custom Data widget implementation
=> feat: Query rule custom data widget

InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.3.0

Tests/InstantSearchTests/Snippets/BannerGuideSnippets.swift
**Summary**
Add snippets for InstantSearch banner guide
=> docs: add banner guide snippets

fastlane/Fastfile, generate_changelog, generate_version
**Summary**
- Automatic changelog and release note generation using _polyglot_ tool
- Add comments to **generate_version** script
=> ci: Full deployment automation

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.4.0

Sources/InstantSearch/Numeric/NumericStepperController.swift, Sources/InstantSearch/Numeric/NumericTextFieldController.swift, Sources/InstantSearch/Stats/LabelStatsController.swift, Sources/InstantSearchCore/MultiIndexHits/Connector/MultiIndexHitsConnector.swift, Sources/InstantSearchCore/Stats/Connector/StatsConnector+Controller.swift
**Summary**
- Add default stepper initializer for NumericStepperController
- Add default text field initializer for NumericTextFieldController
- Add default label initializer for LabelStatsController
- Add empty list as a default value for filterStates parameter in MultiIndexHitsConnector
- Add default textual stats presenter for StatsConnector initializer and `connectController` method
=> feat: Improve API convenience

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.5.0

Sources/InstantSearch/Numeric/NumericRatingController.swift, Sources/InstantSearch/Numeric/RatingControl.swift
**Summary**
Implementation of rating control and  `NumericRatingController` connectable to `FilterState`
Demo is available [here](https://github.com/algolia/instantsearch-ios-examples/pull/18)
**Result**
=> feat: implement RatingControl & NumericRatingController

Sources/InstantSearch/Numeric/NumericRatingController.swift, Sources/InstantSearch/Numeric/NumericRatingRangeController.swift
**Summary**
-  Implement controller conforming to `NumberRangeController` with rating control
- Fix `NumericRatingController` implementation
=> feat: Rating range controller

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.6.0

Readme.md
=> chore: Bump version in Readme

Cartfile, InstantSearch.podspec, Package.swift, Sources/InstantSearchCore/Common/Geolocated.swift
=> fix: broken geolocated conformance

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.6.1

InstantSearch.podspec, Sources/InstantSearchCore/Tracker/FilterTrackable.swift, Sources/InstantSearchCore/Tracker/FilterTracker.swift, Sources/InstantSearchCore/Tracker/HitsAfterSearchTrackable.swift, Sources/InstantSearchCore/Tracker/HitsTracker.swift, Sources/InstantSearchCore/Tracker/InsightsTracker.swift
**Summary**
Remove legacy Insights dependency from the pod spec.
=> fix: remove legacy Insights dependency from the podspec

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.6.2

Sources/InstantSearchCore/QueryBuilder/QueryBuilder+DisjunctiveFaceting.swift, Sources/InstantSearchCore/QueryBuilder/QueryBuilder.swift, Sources/InstantSearchCore/Searcher/SingleIndex/SingleIndexSearcher.swift, Tests/InstantSearchCoreTests/Integration/DisjuncitveAndHierarchicalIntegrationTests.swift, Tests/InstantSearchCoreTests/Integration/DisjunctiveFacetingIntegrationTests.swift, Tests/InstantSearchCoreTests/Integration/HierarchicalIntegrationTests.swift, Tests/InstantSearchCoreTests/Unit/DisjunctiveFacetingsTests.swift, Tests/InstantSearchCoreTests/Unit/QueryBuilderTests.swift
**Summary**
Add possibility of manual disjunctive facets setting up
=> feat: Manual setting of disjunctive facets

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.7.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.8.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.9.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.9.1

Sources/InstantSearchCore/FacetList/FacetListInteractor+MultiIndexSearcher.swift, Sources/InstantSearchCore/FacetList/FacetListInteractor+SingleIndexSearcher.swift, Tests/InstantSearchCoreTests/Misc/SearchResultFacets2.json, Tests/InstantSearchCoreTests/Unit/FacetList/FacetListInteractorTests.swift
**Summary**
This PR introduces a connection between `MultiIndexSearcher` and `FacetListInteractor`
=> feat: implement FacetListInteractor - MultiIndexSearcher connection

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.10.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.11.1

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.12.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.12.1

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.13.1

Sources/InstantSearch/SwiftUI/SuggestionRow.swift, Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor+FilterState.swift
**Summary**
Fixes:
- Archiving issue due to non-isolated SwiftUI declaration ([HelpScout ticket](https://secure.helpscout.net/conversation/1606157997))
- Compiler issue in the `DynamicFacetListInteractor` connection with `FilterState`
=> fix: Compiler & archive issues

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.13.2

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.13.3

Sources/InstantSearch/SwiftUI/FacetList.swift, Sources/InstantSearch/SwiftUI/FacetRow.swift, Sources/InstantSearch/SwiftUI/FilterList.swift, Sources/InstantSearch/SwiftUI/HierarchicalFacetRow.swift, Sources/InstantSearch/SwiftUI/HierarchicalList.swift, Sources/InstantSearch/SwiftUI/HitsList.swift, Sources/InstantSearch/SwiftUI/SearchBar.swift, Sources/InstantSearch/SwiftUI/SuggestionRow.swift, Sources/InstantSearch/SwiftUI/Text+Highlighting.swift, Sources/InstantSearchCore/SwiftUI/CurrentFiltersObservableController.swift, Sources/InstantSearchCore/SwiftUI/DynamicFacetListObservableController.swift, Sources/InstantSearchCore/SwiftUI/FacetListObservableController.swift, Sources/InstantSearchCore/SwiftUI/FilterClearObservableController.swift, Sources/InstantSearchCore/SwiftUI/FilterListObservableController.swift, Sources/InstantSearchCore/SwiftUI/FilterToggleObservableController.swift, Sources/InstantSearchCore/SwiftUI/HierarchicalObservableController.swift, Sources/InstantSearchCore/SwiftUI/HitsObservableController.swift, Sources/InstantSearchCore/SwiftUI/LoadingObservableController.swift, Sources/InstantSearchCore/SwiftUI/NumberRangeObservableController.swift, Sources/InstantSearchCore/SwiftUI/QueryInputObservableController.swift, Sources/InstantSearchCore/SwiftUI/RelevantSortObservableController.swift, Sources/InstantSearchCore/SwiftUI/SelectableSegmentObservableController.swift, Sources/InstantSearchCore/SwiftUI/StatsObservableController.swift, Sources/InstantSearchCore/SwiftUI/StatsTextObservableController.swift, Sources/InstantSearchCore/SwiftUI/SwitchIndexObservableController.swift
**Summary**
This PR fixes the compiler errors which occur during the archiving using Xcode 13.
Closes #194
=> fix: Xcode 13 archive issues

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.13.4

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.13.5

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.14.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.15.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.16.0

.github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/pods.yml, .github/workflows/swift.yml, fastlane/Fastfile
**Summary**
Adds CI checks using GitHub Actions
=> chore: Implement GitHub actions CI/CD

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.17.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.18.0

.github/workflows/carthage.yml, .github/workflows/swift.yml
**Summary**
- Rename Carthage action
- Launch test only for PR instead of each commit
=> chore: Update GitHub actions

Sources/InstantSearchCore/Hits/Connector/HitsConnector+GeoSearch.swift, Sources/InstantSearchCore/Hits/HitsInteractor+PlacesSearcher.swift, Sources/InstantSearchCore/Pagination/PageLoadable.swift, Sources/InstantSearchCore/Searcher/Places/PlacesSearcher.swift
**Summary**
This PR deprecates Places components since this feature has been sunset.
=> chore: deprecate Places components

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.19.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.19.1

Cartfile, InstantSearch.podspec, InstantSearch.xcodeproj/project.pbxproj, InstantSearch.xcodeproj/xcshareddata/xcschemes/InstantSearch-Package.xcscheme, Package.swift, Sources/InstantSearch/MultiIndexHits/CollectionView/MultiIndexHitsCollectionController.swift, Sources/InstantSearch/MultiIndexHits/CollectionView/MultiIndexHitsCollectionViewDataSource.swift, Sources/InstantSearch/MultiIndexHits/CollectionView/MultiIndexHitsCollectionViewDelegate.swift, Sources/InstantSearch/MultiIndexHits/TableView/MultiIndexHitsTableController.swift, Sources/InstantSearch/MultiIndexHits/TableView/MultiIndexHitsTableViewDataSource.swift, Sources/InstantSearch/MultiIndexHits/TableView/MultiIndexHitsTableViewDelegate.swift, Tests/InstantSearchCoreTests/Integration/DisjuncitveAndHierarchicalIntegrationTests.swift, Tests/InstantSearchCoreTests/Integration/DisjunctiveFacetingIntegrationTests.swift, Tests/InstantSearchCoreTests/Integration/HierarchicalIntegrationTests.swift, Tests/InstantSearchCoreTests/Integration/OnlineTestCase.swift, Tests/InstantSearchCoreTests/Unit/Searcher/AnswersSearcherTests.swift, Tests/InstantSearchCoreTests/Unit/TelemetryTests.swift
**Summary**
This PR removes the deprecation warnings occurring in the Xcode.
=> chore: remove deprecation warnings

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.20.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.20.1

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.21.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.21.1

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.21.2

.github/workflows/lint.yml
**Summary**
Updates the `SwiftLint lint` action to make it appear correctly in the checks list.
=> chore: Update SwiftLint action

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.22.0

Cartfile, InstantSearch.podspec, Package.swift, Sources/InstantSearchCore/Helper/CoreUserAgentSetter.swift, Sources/InstantSearchCore/Searcher/Searcher.swift, Sources/InstantSearchInsights/Helpers/InsightsUserAgentSetter.swift, Sources/InstantSearchInsights/Helpers/UserAgentSetter.swift, Sources/InstantSearchInsights/Logic/Insights.swift, Sources/InstantSearchSwiftUI/DataModel/HitsObservableController.swift, Tests/InstantSearchCoreTests/Integration/OnlineTestCase.swift, Tests/InstantSearchInsightsTests/Unit/UserAgentTest.swift
**Summary**
This PR adds a specific user-agent extension for Insights
**Result**
Insights user-agent appears in the events logs
=> feat(Insights): add user-agent extension

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.23.0

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.24.0

.github/workflows/deployment.yml, CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.25.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.25.1

CHANGELOG.md, InstantSearch.podspec, Readme.md, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new minor version 7.26.0

CHANGELOG.md, InstantSearch.podspec, Sources/InstantSearchCore/Helper/Version+Current.swift
=> chore: Deploying new patch version 7.26.1
