.gitattributes

Normally the documentation doesn't count in the top bar with regard to languages being used, but we use `docgen` as a folder name, so it doesn't get picked up automatically. This PR fixes that.

chore(docgen): mark as documentation for GitHub

---

Sources/Library/InstantSearch.swift

This is so that it is not confused with other InstantSearch libraries

fix(user-agent): Change user agent from "InstantSearch" to "InstantSearch iOS"

---

Readme.md

This is to be consistent with the other libs

docs(readme): add links to other InstantSearch flavours

---

Cartfile.resolved
InstantSearch.podspec
InstantSearch.xcodeproj/xcshareddata/xcschemes/InstantSearch.xcscheme
Readme.md
Sources/InstantSearch.swift
Tests/ConfigureInstantSearchTests.swift
Tests/ObjectiveCBridgingTests.m
Tests/WidgetTests.swift
docgen/src/getting-started-programmatic.md
docgen/src/getting-started.md
fastlane/Fastfile
instantsearch.xcodeproj/project.pbxproj

```
pod 'InstantSearch', '~> 2.0.0' // default for everything (equivalent to /UI)
pod 'InstantSearch/UI' // for access to everything
pod 'InstantSearch/Core' // for access to everything except the UI widgets
pod 'InstantSearch/Client' //for access only to the API Client
```
Note also that we're renaming our pod InstantSearch-iOS to InstantSearch since it makes more sense
@robertmogos @PLNech @mthuret  would love your opinion on the final naming of `/UI` `/Core` `/Client` since they won't change in the future.

refac(pod): introduce clear 3 api layers in CocoaPods

---

docgen/src/data/communityHeader.json

The link to the API Reference in the [community website documentation](https://community.algolia.com/instantsearch-ios/) is broken:

doc(menu): fix API Reference 404

---

Sources/Concrete/ViewModel/RefinementMenuViewModel.swift

**Summary**
Bug where refinement list was not being reloaded when no facet results, and if the refinement list was in the same view controller as other widgets 
Bug submitted from [discourse ](https://discourse.algolia.com/t/refinementcollectionwidget-facets-not-updating-when-params-added-to-searcher/6661/5).
**Result**
Reload refinements when that's the case.

reload view when empty result in refinement list

---

InstantSearch.podspec
InstantSearchTestsHost/Info.plist
Sources/Controller/Hits/CollectionView/HitsCollectionController.swift
Sources/Controller/Hits/CollectionView/HitsCollectionViewDataSource.swift
Sources/Controller/Hits/CollectionView/HitsCollectionViewDelegate.swift
Sources/Controller/Hits/TableView/HitsTableViewDataSource.swift
Sources/Controller/Hits/TableView/HitsTableViewDelegate.swift
Sources/Controller/MultiIndexHits/CollectionView/MultiIndexHitsCollectionController.swift
Sources/Controller/MultiIndexHits/CollectionView/MultiIndexHitsCollectionViewDataSource.swift
Sources/Controller/MultiIndexHits/CollectionView/MultiIndexHitsCollectionViewDelegate.swift
Sources/Controller/MultiIndexHits/TableView/MultiIndexHitsTableViewDataSource.swift
Sources/Controller/MultiIndexHits/TableView/MultiIndexHitsTableViewDelegate.swift
Sources/FatalErrorUtil.swift
Sources/Info.plist
Tests/CollectionViewHitsControllerTests.swift
Tests/CollectionViewMultiIndexHitsControllerTests.swift
Tests/FatalErrorTest.swift
Tests/Info.plist
Tests/TableViewHitsControllerTests.swift
Tests/TableViewMultiIndexHitsControllerTests.swift
Tests/TestHitsSource.swift
Tests/TestMultiHitsDataSource.swift
instantsearch.xcodeproj/project.pbxproj

**Features:**
- A possibility to set a template table/collectionView cell provider for a hit which should be present in the collection, but result page of which is not loaded yet.
**Fixes:**
- Private accessors dataSource/delegate in HitsCollectionController set public.

Release v5.1.0

---

Cartfile

This fix removes patch version from dependencies described in the Cartfile. 
As a result, InstantSearch will always install last minor versions of its dependencies.

Remove patch version dependency from Cartfile

---

Sources/InstantSearchCore/FacetList/FacetListInteractor+Controller.swift
Sources/InstantSearchCore/FacetList/FacetListInteractor+FilterState.swift
Sources/InstantSearchCore/FilterState/Accessors/GroupAccessor.swift
Sources/InstantSearchCore/FilterState/FilterState+Commands.swift
Sources/InstantSearchCore/FilterState/FilterState.swift
Sources/InstantSearchCore/Segmented/SelectableFilterInteractor+FilterState.swift
Sources/InstantSearchCore/Toggle/ToggleFilter+FilterState.swift
Tests/InstantSearchCoreTests/Unit/CurrentFilters/CurrentFiltersControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/CurrentFilters/CurrentFiltersFilterStateConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/FacetList/FacetListControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/FacetList/FacetListFacetSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/FacetList/FacetListFilterStateConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/FacetList/FacetListSingleIndexSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorFilterStateConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/MultiSourceHitsReloaderTests.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/QueryInputControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/QueryInputSearcherConnectionTests.swift

- Fix leaks occurring after connections establishment between  `FacetListInteractor` - `FilterState` - `FacetListController` (IFM-554)
- Fix leak occurring while `FilterState`  captures itself in consequence of the `onChange` event triggering
- Add unit tests checking if InstantSearch components leaked as a result of their connection

fix: Connections memory leaks

---

Package.swift
Sources/InstantSearchCore/Searcher/Facet/FacetSearcher.swift
Sources/InstantSearchCore/Searcher/MultiIndex/MultiIndexSearcher.swift
Sources/InstantSearchCore/Searcher/Places/PlacesSearcher.swift
Sources/InstantSearchCore/Searcher/Searcher.swift
Sources/InstantSearchCore/Searcher/SingleIndex/SingleIndexSearcher.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/QueryInputSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/TestSearcher.swift
Tests/InstantSearchCoreTests/Unit/Searcher/MultiIndexSearcherTests.swift
Tests/InstantSearchCoreTests/Unit/Searcher/SingleIndexSearcherTests.swift

This PR add a few demanded functionalities to index searchers:
- Optional `shouldTriggerSearch` closure defining if an actual request must be performed when `search()` function called
- `onIndexChanged` event for `MultiIndexSearcher`
- Code documentation improvements

Index searchers improvements

---

Package.swift
Sources/InstantSearch/AdvancedConnectors/MultiIndexSearchConnector+UIKit.swift
Sources/InstantSearch/AdvancedConnectors/SingleIndexSearchConnector+UIKit.swift
Sources/InstantSearch/Hits/CellConfigurable.swift
Sources/InstantSearch/Hits/CellConfigurator.swift
Sources/InstantSearch/Hits/CollectionView/HitsCollectionViewController.swift
Sources/InstantSearch/Hits/TableView/HitsTableViewController.swift
Sources/InstantSearchCore/AdvancedConnectors/MultiIndexSearchConnector.swift
Sources/InstantSearchCore/AdvancedConnectors/SingleIndexSearchConnector.swift
Sources/InstantSearchCore/FacetList/FacetListConnector.swift
Sources/InstantSearchCore/QueryBuilder/QueryBuilder.swift
Sources/InstantSearchCore/Searcher/MultiIndex/MultiIndexSearcher.swift
Tests/InstantSearchCoreTests/Unit/Connectors/MultiIndexSearchConnectorTests.swift
Tests/InstantSearchCoreTests/Unit/Connectors/SingleIndexSearchConnectorTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorFilterStateConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/TestHitsController.swift
Tests/InstantSearchCoreTests/Unit/MultiIndexHits/MultiIndexHitsInteractorControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/MultiIndexHits/MultiIndexHitsInteractorSearcherConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/QueryInputControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/QueryInput/QueryInputSearcherConnectionTests.swift

This PR adds to **InstantSearch**:
- `SingleIndexSearchConnector` & `MultiIndexSearchConnector` which establish the necessary connections for basic single and multi-index search experiences respectively. They encapsulate `QueryInput`, `Searcher`, `Hits` components and provide convenient initialisers including `Controllers`.
- `HitsTableViewController` and `HitsCollectionViewController` implementations to use with with connectors mentioned above for quick demos and prototyping.
- Memory leak fix in `MultiIndexSearcher` due to `PageLoader` initialization
Components intoduced in this PR will be used in the updated Getting Started Guide.

Advanced connectors & lightweight Hits controllers

---

Sources/InstantSearch/AdvancedConnectors/MultiIndexSearchConnector+UIKit.swift
Sources/InstantSearch/AdvancedConnectors/SingleIndexSearchConnector+UIKit.swift
Sources/InstantSearch/SearchBox/TextFieldController.swift

This PR fixes condition compiling issue for tvOS due to missing `UISearchBar.searchTextField` property for this platform.

Fix tvOS conditional compiling issue

---

Sources/InstantSearchCore/Sequencer/Sequencer.swift
Tests/InstantSearchCoreTests/Unit/SequencerTest.swift

**Summary**
This PR refactor Sequencer implementation to make it thread-safe and to avoid crashes occurring in Xcode 12
Resolves #128

fix: Xcode 12 crash due to unsynchronised sequencer

---

Sources/InstantSearch/Numeric Comparator/NumericStepperController.swift
Sources/InstantSearch/Numeric Comparator/NumericTextFieldController.swift
Sources/InstantSearchCore/Number/Connector/FilterComparisonConnector+Controller.swift
Sources/InstantSearchCore/Number/Connector/FilterComparisonConnector.swift
Sources/InstantSearchCore/Number/FilterComparison+Controller.swift
Sources/InstantSearchCore/Number/NumberController.swift

**Summary**
- Add connection between `NumberInteractor` and `Searcher` in `FilterComparisonConnector` to fetch bounds from the `SearchResponse` on each search
- Add `setBounds` method to `NumberController`. 
- Add `setBounds` method to `NumberController` implementations of the __InstantSearch__

feat: Connection between Numeric filter and Searcher to fetch numeric value bounds

---

Sources/InstantSearchCore/AdvancedConnectors/MultiIndexSearchConnector.swift
Sources/InstantSearchCore/AdvancedConnectors/SingleIndexSearchConnector.swift
Sources/InstantSearchCore/Loading/Connector/LoadingConnector+Controller.swift
Sources/InstantSearchCore/Loading/Connector/LoadingConnector.swift
Sources/InstantSearchCore/Loading/LoadingInteractor+Searcher.swift
Sources/InstantSearchCore/QueryInput/Connector/QueryInputConnector+Controller.swift
Sources/InstantSearchCore/QueryInput/Connector/QueryInputConnector.swift

**Summary**
Remove the necessity to specify a `Searcher` generic type in `LoadingConnector` and `QueryInputConnector`.
Makes the API more straightforward without any bad impact on the consistency and type-safety.

refactor: Suppress generic requirements in `LoadingConnector` and `QueryInputConnector`

---

Cartfile
InstantSearch.podspec
Package.swift
Sources/InstantSearchCore/Common/Hit+Place.swift
Sources/InstantSearchCore/Highlighting/NSAttributedString+TaggedString.swift

**Summary**
Fix for compatibility with [Swift Client change](https://github.com/algolia/algoliasearch-client-swift/pull/689).

chore: Create a mutable copy of `TaggedString` to access its lazy properties

---

Cartfile
InstantSearch.podspec
Package.swift

**Summary**
Bump Swift API client dependencies in the Package, podspec and the Cartfile

fix: Bump API client dependencies

---

Sources/InstantSearchInsights/Logic/EventTracker.swift
Sources/InstantSearchInsights/Logic/Insights.swift
Tests/InstantSearchInsightsTests/Unit/InsightsTests.swift

**Summary**
[Crash report](https://secure.helpscout.net/conversation/1590238758).
The reason of this crash is the issue in the Swift - Objective-C interoperability [explained here](https://stackoverflow.com/questions/61006622/exc-bad-access-in-swift-isuniquelyreferenced-nonnull-native-when-accessing-swift).
This PR fixes this crash by removing the Objective-C leftovers of the standalone Insights library.

fix: Remove Objective-C leftovers from the Insights causing the crash

---

InstantSearch.podspec
Package.swift
Readme.md
Sources/InstantSearchCore/Hits/HitsInteractor.swift
Sources/InstantSearchSwiftUI/DataModel/CurrentFiltersObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/DynamicFacetListObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/FacetListObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/FilterClearObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/FilterListObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/FilterToggleObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/HierarchicalObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/HitsObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/LoadingObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/NumberRangeObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/QueryInputObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/RelevantSortObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/SelectableSegmentObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/StatsObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/StatsTextObservableController.swift
Sources/InstantSearchSwiftUI/DataModel/SwitchIndexObservableController.swift
Sources/InstantSearchSwiftUI/View/FacetList.swift
Sources/InstantSearchSwiftUI/View/FacetRow.swift
Sources/InstantSearchSwiftUI/View/FilterList.swift
Sources/InstantSearchSwiftUI/View/HierarchicalFacetRow.swift
Sources/InstantSearchSwiftUI/View/HierarchicalList.swift
Sources/InstantSearchSwiftUI/View/HitsList.swift
Sources/InstantSearchSwiftUI/View/SearchBar.swift
Sources/InstantSearchSwiftUI/View/SuggestionRow.swift
Sources/InstantSearchSwiftUI/View/Text+Highlighting.swift

**Summary**
This PR separates the SwiftUI components to a particular InstantSearchSwiftUI product.
The InstantSearch/SwiftUI Cocoapods subspec will still work as before.

refactor: Separate the InstantSearchSwiftUI product

---

Sources/InstantSearchCore/Hits/HitsInteractor.swift

**Summary**
This PR exposes the `pageCleanUpOffset` infinite scrolling parameter defining how many pages of hits might be kept in memory before and after the current page.
Fixes #207

feat(infinite scrolling): Expose the `pageCleanUpOffset` parameter

---

.github/workflows/carthage.yml
Cartfile
InstantSearch.podspec
InstantSearch.xcodeproj/AlgoliaSearchClient_Info.plist
InstantSearch.xcodeproj/InstantSearchCoreTests_Info.plist
InstantSearch.xcodeproj/InstantSearchCore_Info.plist
InstantSearch.xcodeproj/InstantSearchInsightsTests_Info.plist
InstantSearch.xcodeproj/InstantSearchInsights_Info.plist
InstantSearch.xcodeproj/InstantSearchSwiftUITests_Info.plist
InstantSearch.xcodeproj/InstantSearchSwiftUI_Info.plist
InstantSearch.xcodeproj/InstantSearchTelemetry_Info.plist
InstantSearch.xcodeproj/InstantSearchTests_Info.plist
InstantSearch.xcodeproj/InstantSearch_Info.plist
InstantSearch.xcodeproj/Logging_Info.plist
InstantSearch.xcodeproj/SwiftProtobuf_Info.plist
InstantSearch.xcodeproj/project.pbxproj
InstantSearch.xcodeproj/project.xcworkspace/contents.xcworkspacedata
InstantSearch.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
InstantSearch.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
InstantSearch.xcodeproj/xcshareddata/xcschemes/InstantSearch-Package.xcscheme
Package.swift
carthage-prebuild

**Summary**
Starting from version 7.16.0 and due to change in the Swift Package Manager project generation behaviour, it's impossible to build InstantSearch using Carthage dependency manager.
Fix #218 
**Result**
Latest InstantSearch version builds successfully with Carthage.

fix: Carthage build

---

Examples/Examples.xcodeproj/project.pbxproj
Sources/InstantSearchCore/Number/Connector/FilterComparisonConnector.swift
Sources/InstantSearchSwiftUI/DataModel/NumberObservableController.swift

**Summary**
- Move `NumberObservableController` from Examples to library level
- Set default values for `number` and `operator` values of `FilterComparisonConnector`

feat: NumberObservableController implementation

---

Sources/InstantSearchCore/Hits/HitsInteractor.swift
Sources/InstantSearchSwiftUI/DataModel/HitsObservableController.swift
Tests/InstantSearchCoreTests/Unit/PageMapTests.swift

**Summary**
The existing implementation of `HitsObservableController` uses `getCurrentHits` function  of `HitsInteractor` to build an observable list of hits. That's why the infinite scrolling didn't work correctly due optimization which keeps only 4 most recents pages of hits in memory. 
This PR adds `hits` computed property in `HitsInteractor` which ensures the correct hits pages to hits list by presenting the hits of unloaded pages as `nil` values.  
**Result**
Inifinite scrolling works correctly with `HitsObservableController`.

fix: SwiftUI infinite scrolling issue

---

Examples/Showcase/Filter/FilterNumericRange/FilterNumericRangeDemoController.swift
Examples/Showcase/Filter/FilterNumericRange/FilterNumericRangeDemoViewController.swift
InstantSearch.xcodeproj/project.pbxproj
Sources/InstantSearchCore/Number/Boundable+HitsSearcher.swift
Sources/InstantSearchCore/Number/Boundable+SearchResultProvider.swift

**Summary**
- Deprecate the unused  `BoundableSearchResultProvderConnection` to remove the ambiguity with `BoundableHitsSearcherConnection `.
-  Make the Number Range Demo more interactive by adding the search bar and stats

chore: deprecate Boundable <-> Search Result Provider connection

---

Examples/Showcase/Facet/HierarchicalFacets/HierarchicalDemoController.swift
Sources/InstantSearchCore/Hierarchical/HierarchicalInteractor+FilterState.swift
Sources/InstantSearchCore/Hierarchical/HierarchicalInteractor.swift

**Summary**
Calling `onSelectionChanged` on already selected item doesn't introduce any change to the hierarchical tree.
The expected behaviour would be to deselect the item and update the hierarchical tree.

fix(hierarchical): deselect item

---

.github/workflows/deployment.yml

**Summary**
- Update fastlane action version to 2.2.1 supporting verbose output
- Make the fastlane step output verbose

chore: update fastlane action and make it verbose

---

Sources/InstantSearchCore/FilterState/GroupStorage.swift
Sources/InstantSearchCore/Hierarchical/HierarchicalInteractor+FilterState.swift

**Summary**
Clearing of `FilterState` using Clear Filters widget doesn't correctly reset the hierarchical group, causing the incorrect state for future searches and crashes. 
This PR fixes the clearing logic.
Fix #251

fix(hierarchical): Hierarchical facets clearing

---

Sources/InstantSearchCore/Hits/HitsExtractable.swift
Sources/InstantSearchCore/Hits/HitsInteractor.swift
Sources/InstantSearchCore/Pagination/SearchResults+PageMap.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorControllerConnectionTests.swift
Tests/InstantSearchCoreTests/Unit/Hits/HitsInteractorTests.swift

**Summary**
Currently `HitsInteractor` supports only the camel case case since it uses the default `JSONDecoder` constructor, so the client might add `CodingKeys` per model to support snake case.
**Result**
`HitsInteractor` provides `jsonDecoder` property which can be set in the initialiser or as property, so it's possible to set a custom decoder for hits. 
Fix #247

feat(HitsInteractor): ability to set a custom json decoder to hits interactor

---

Sources/InstantSearchCore/Searcher/AbstractSearcher.swift
Sources/InstantSearchCore/Searcher/IndexSearcher.swift

**Summary**
The `IndexSearcher` might be open, so users can subclass it with a custom `SearchService` for backend search implementation.
The `AbstractSearcher` might be open as well as a superclass of `IndexSearcher`.

fix(Searcher): set open access level  for AbstractSearcher and IndexSearcher 

---

Sources/InstantSearchCore/Hits/HitsInteractor.swift

**Summary**
Add missing propagation of the json decoder parameter from the convenient initialiser to designated initialiser.

fix(HitsInteractor): Missing propagation of json decoder property to designated initializer

---

Sources/InstantSearchCore/DynamicFacets/AttributedFacets.swift
Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor+Searcher.swift
Tests/InstantSearchCoreTests/Unit/DynamicFacets/DynamicFacetListInteractorTests.swift

**Summary**
The disjunctive faceting doesn't work correctly with `DynamicFacetList` properly configured for disjunctive faceting. 
This happens due to ignoring the `disjunctiveFacets` property of the `SearchResponse` which contains the proper facet values when disjunctive faceting applied. 
**Result**
The disjunctive faceting with `DynamicFacetList` works correctly. 
Backed by unit test.

fix: update `orderedFacets` of `DynamicFacetListInteractor` ignores `disjunctiveFacets`

---

Sources/InstantSearchCore/Helper/Array+Ranges.swift
Sources/InstantSearchCore/Searcher/Multi/AbstractMultiSearcher.swift
Sources/InstantSearchCore/Searcher/Multi/MultiSearchError.swift
Tests/InstantSearchCoreTests/Unit/ArrayExtensions.swift
Tests/InstantSearchCoreTests/Unit/Searcher/MultiSearcherTests.swift

**Summary**
In `AbstractMultiSearcher` during the extraction of the subranges of the results, there is no check if the subrange bounds are compatible with the results size (index out of bounds exception). In some circumstances this can provoke [a crash](https://algolia.atlassian.net/browse/CR-2158?atlOrigin=eyJpIjoiOTRmYmI5NjI4OTRlNGYyOWJjYjMwYWUxNWFjOGE4M2EiLCJwIjoiaiJ9).
**Result**
The crash conditions are checked and an error `MultiSearchError.rangeError` is thrown to prevent it.

fix(multi-search): crash in case of requests-results count mismatch

---

.github/workflows/format.yml
Sources/InstantSearchInsights/Logic/EventProcessor.swift
Tests/InstantSearchInsightsTests/Unit/EventsProcessorTests.swift

**Summary**
`EventsProcessor` of `Insights` package filters out event in package by acceptance condition (event was captured not longer than 4 days ago). 
If all events in the package don't satisfy this condition, an empty payload will be sent. 
This PR adds a check to avoid useless network calls in this case.
**Result**
No network call happens if no event satisfy the acceptance criteria

fix: send empty events packages if all non statisfying condition

---

Sources/InstantSearchCore/DynamicFacets/Connector/DynamicFacetListConnector+Controller.swift
Sources/InstantSearchCore/DynamicFacets/Connector/DynamicFacetListConnector.swift
Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor+FilterState.swift
Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor.swift

**Summary**
This PR adds `defaultSelectionMode` and  `defaultFilterGroupType` parameters to `DynamicFacetList` components to customize their default behaviour. It will replace the hardcoded `single` selection, `and` filter group type. 
**Result**
Developers allowed to set the default selection type and filter group type for `DynamicFacetList` component instead of hardcoded single selection and conjunctive (`and`) group type. It helps to avoid boilerplate code in case of big amount of facet attributes which supposed to behave differently from the hardcoded values.

feat(dynamicFacetList): add default selection & faceting parameters

---

Examples/Examples/Demo.swift
Examples/Examples/DemoViewControllerFactory.swift
Examples/Examples/ShowcaseDemo.swift
Examples/Examples/ShowcaseDemoViewControllerFactory.swift
Examples/Guide/GettingStartedUIKitGuide/GettingStartedSearchViewController.swift
Examples/MultiIndex/MultiIndex.SearchResultsController.swift
Examples/Shared/UIColor+Convenience.swift
Examples/Shared/View/Product/ProductRow.swift
Examples/Showcase/Facet/FacetListPersistentSelection/FacetListPersistentSelectionDemoController.swift
Examples/Showcase/Filter/FilterNumericComparison/FilterNumericComparisonDemoViewController.swift
Sources/InstantSearch/MultiIndexHits/CollectionView/MultiIndexHitsCollectionController.swift
Sources/InstantSearchCore/FilterMap/FilterMapInteractor+Controller.swift
Sources/InstantSearchCore/FilterMap/FilterMapInteractor+FilterState.swift
Sources/InstantSearchCore/FilterMap/FilterMapInteractor+Searcher.swift
Sources/InstantSearchCore/FilterState/FIlter/Groups/OrFilterGroup.swift
Sources/InstantSearchCore/FilterState/FilterGroupID.swift
Sources/InstantSearchCore/Hierarchical/HierarchicalInteractor+Controller.swift
Sources/InstantSearchCore/Number/Boundable+SearchResultProvider.swift
Sources/InstantSearchCore/Searcher/Hits/HitsSearcher.swift
Sources/InstantSearchCore/Tracker/HitsAfterSearchTrackable.swift
Sources/InstantSearchCore/Tracker/HitsTracker.swift
Sources/InstantSearchInsights/Logic/EventTracker.swift
Sources/InstantSearchInsights/Protocols/EventTrackable.swift
Tests/InstantSearchCoreTests/Unit/Searcher/HitsSearcherTests.swift

Closes [FX-2240](https://algolia.atlassian.net/browse/FX-2240)
**Summary**
Implements automatic hits view event tracking received in the search response of the HitsSearcher. 
Adds `hitsTracker` as a field of HitsSearcher for more convenient events tracking. 
[FX-2240]: https://algolia.atlassian.net/browse/FX-2240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(insights): automatic hits view events tracking

---

Sources/InstantSearchCore/NumberRange/NumberRangeInteractor.swift

**Summary**
`NumberRangeConnector` sends 2 redundant search requests during the initialization. This patch removes this extra-calls.
**Result**
No unnecessary search requests while using the `NumberRangeConnector` component.

fix(NumberRangeConnector): redundant search request sent by NumberRangeConnector

---

Sources/InstantSearchCore/Tracker/HitsTracker.swift

**Summary**
If hits results page contains more than 20 hits, the hits view events automatically sent by the `HitsSearcher` are rejected by Insights. This PR adds an automatic chunking of the hits list into chunks of 20 objects to avoid this situation. 
**Result**
All the hits view events are correctly sent even if the page size is bigger than 20 hits.

feat(HitsTracker): add automatic object ids chunking

---

Sources/InstantSearchCore/DynamicFacets/DynamicFacetListInteractor+FilterState.swift

**Summary**
This PR adds recalculation of the selections in the `DynamicFacetListInteractor` on update of facets values. This is useful when the selected facets are predefined in the FilterState, but no selections update happens until the user's selection.
**Result**
The selection state of the `DynamicFacetListInteractor` is correct even if the filters are preselected in the `FilterState`.

fix(dynamic facets): recalculate selections on facets order change

---

Examples/Showcase/Filter/FilterNumericRange/NumericRangeController.swift
Examples/Showcase/Search/PaginationSingleIndex/SearchDemoSwiftUI.swift

**Summary**
- Fix compilation issue due to usage of `HitsList` instead of `InfiniteList` component
- Add UI invalidation logic for the numeric range demo

fix: Examples app

---

Examples/Examples.xcodeproj/project.pbxproj
Examples/QuerySuggestions/QuerySuggestionsDemoView.swift
Examples/QuerySuggestions/SceneDelegate.swift
Examples/Showcase/Search/PaginationSingleIndex/SearchDemoSwiftUI.swift
Sources/InstantSearchCore/Hits/InfiniteScrolling/HitsSearcher+InfiniteScrollViewModel.swift
Sources/InstantSearchCore/Hits/InfiniteScrolling/PaginatedDataViewModel.swift
Sources/InstantSearchCore/Searcher/AbstractSearcher.swift
Sources/InstantSearchCore/Searcher/SearchService/AlgoliaSearchService.swift
Sources/InstantSearchSwiftUI/View/InfiniteList.swift
Sources/InstantSearchSwiftUI/View/SuggestionRow.swift

**Summary**
Adds SwiftUI query suggestions example

chore: SwiftUI Query Suggestion example

---

Sources/InstantSearchCore/Searcher/Hits/HitsSearcher.swift

**Summary**
Add `isAutoSendingHitsViewEvents` to `HitsSearcher`. If set to `true` insights view events are automatically sent.
The parameter defaults to `false`.
FX-2875

fix(insights): control auto sending events w/ `isAutoSendingHitsViewEvents`

---

InstantSearch.podspec
Package.swift

**Summary**
This PR updates minimum supported platform versions to resolve a compatibility issue with AlgoliaSearchClient.
**Result**
Platform are synced, and library can be built correctly with latest versions of AlgoliaSearchClient.

fix: align versions with api client

---

.github/workflows/deployment.yml

**Summary**
Updates deployment github action, adds manual trigger to launch it.

chore: update deployment action

---

.editorconfig
.github/workflows/pods.yml
.github/workflows/swift.yml
.gitignore
Cartfile
InstantSearch.podspec
Package.swift
Sources/InstantSearchCore/Pagination/PageMap.swift
Sources/InstantSearchCore/Searcher/MultiIndex/MultiIndexSearcher.swift
Sources/InstantSearchCore/SortBy/Connector/SortByConnector+Controller.swift
Sources/InstantSearchCore/SortBy/Connector/SortByConnector.swift
Tests/InstantSearchCoreTests/Unit/DecodingErrorPrettyPrinterTests.swift

**Summary**
This PR updates a PageMap extension so that it conforms more closely to the Sequence protocol, which seems more restrictive with Xcode 16.
This also updates the CI to run tests on Xcode 16 and fixes a number of failing jobs.
**Result**
- project can be built on Xcode 16
- ci workflow works again
Fixes #318

fix: conform pagemap extension to sequence protocol

---

Cartfile
InstantSearch.podspec
Package.swift

**Summary**
This PR bumps the pinned version of Protobuf to prevent incompatibility errors during cocoapods pre publishing checks.

chore: bump protobuf

---

.github/workflows/carthage.yml
.github/workflows/pods.yml
.github/workflows/swift.yml
Tests/InstantSearchCoreTests/Unit/DecodingErrorPrettyPrinterTests.swift

**Summary**
Since Xcode 16 release in September, the beta version cannot be found on the macos-14 GitHub runner image, but in the new macos-15 runner image.
This PR updates the reference to ensure tests are run and pass for Xcode 16.

ci: update actions runner to support released xcode 16

---

Sources/InstantSearchCore/Pagination/PageMap.swift

**Summary**
This PR addresses [this concern](https://github.com/algolia/instantsearch-ios/pull/321#discussion_r1692760104) by updating the `PageMap` iterator logic to prevent unnecessary copying of page items, enhancing overall performance.
**Result**
- Performance tuning for `PageMap` iteration
- Project still compiles successfully in Xcode 16

Optimize PageMap Iterator

---

Sources/InstantSearchCore/SortBy/Connector/SortByConnector.swift
Tests/InstantSearchCoreTests/Unit/Connectors/SortByConnectorTests.swift

**Summary**
This PR fixes a regression that occurred in https://github.com/algolia/instantsearch-ios/pull/321 which resulted in `SortByConnector` improperly defining its indices array, attributing the first index name for all values of the array.
Fixes #327

fix(sortby): properly map indices names

---

CHANGELOG.md

**Summary**
Last PR was merged without squashing causing the generated changelog for the latest version to be incorrect. This PR fixes it. Updated the corresponding release description as well.

chore: update changelog to follow generated format
